### PR TITLE
IAS Internal Docs

### PR DESCRIPTION
**Pull request by ksheurs**
This PR adds the internal endpoints and params to support customer creation/retrieving for IAS billing.

@charlietran is also working on a more detailed article on http://dev.vhx.tv/integrations/ for more of a readable walk through.

### CODE REVIEW

**Comment by scottusrobus** [comment]
👍

**Comment by yasi** [comment]
can we merge?

**Comment by ksheurs** [comment]
@yasi I'm waiting on charlie's addition to dev.vhx.tv (which this PR references). Let's discuss here https://app.asana.com/0/204939087856629/257274362522755

**Comment by scottusrobus** [comment]
@ksheurs @charlietran @yasi gonna merge both PRs in!

**Pull request merged**
