### PR TITLE
Analytics api

### PR DESCRIPTION
**Pull request by osetinsky**
Adds analytics information to our API documentation.

@ksheurs @scottusrobus open to your feedback on this. Writing some of the documentation alerted me to a few potential issues with the responses from our analytics API:

a) the self href seems to be formatted incorrectly on api.vhx.tv:

http://api.crystal.dev/analytics?by=&from=2016-05-01+17:18:01+-0400&page=&per_page=&to=2016-06-01+17:18:01+-0400&type=video.platforms

I think it should instead return utc times in utc.iso8601 and remove the empty params (by, page, per_page).

b) in our category reports (platforms, geography, subtitles), we are returning the video_id in each of the categories as:

```
  },
  "to": "2016-06-01T23:59:59Z",
  "from": "2016-05-24T00:00:00Z",
  "type": "video.subtitles",
  "data": [
    {
      "video_id": "70917",
      "country": "United States",
      "plays": "5805",
      "finishes": "4289",
      "seconds": "8581460",
      "country_code": "USA"
    },
    {
      "video_id": "70917",
      "country": "United Kingdom",
      "plays": "229",
      "finishes": "139",
      "seconds": "290870",
      "country_code": "GBR"
    },
```

we should probably just include video_id once at the same level as to/from/type.

c) I'm wondering if we should include in the response a link to the video in question (?)

### CODE REVIEW

**Comment by scottusrobus** [comment]
Thanks for getting this started @osetinsky! Glad to get this in there.

A few thoughts:
1. With regards to the empty params (per_page, by, etc) — if that's in reference to what the ajax calls look like in the admin that's due to the way our VHX.Request JS class is setup. I have a task to clean that up: https://app.asana.com/0/5019871452874/117936064764417
2. I don't think we need 4 sections for each of the Video Analytics types. In general each section is a different endpoint for a resource. Those requests and responses are all a similar format (same parameters and URL) except you just pass a different `type`. Responses are mostly the same (except for the one changing property). You can show what the different `type` options are under the type argument in the argument table.  
3. We should add the other report types @sgrshah created for the dashboard as well. These different types it might make sense to have different sections, if the responses are drastically different. Not sure though, since technically it is the same endpoint.
4. We need to add these to our client libraries! I'll work on PHP and Node, and @osetinsky or @sgrshah if either of you could add it to the Ruby client would be great!

@ksheurs let me know if you have any thoughts on my thoughts :)

**Comment by ksheurs** [comment]
Thanks for getting this going, Paul! To answer your questions in the PR:

a) Is this a big change to pass dates from JS as iso8601?
b) Yea agree!
c) Let's hold off for now. 

Re: Scott's feedback:

Agree that analytics is a unique section (and doesn't need sub sections per each report). We should have a sub sections for defining this resource + it's common arguments (type, by, from, to) + time series vs aggregate + the common response structure (by, from, to, data: {}, etc).

From there, maybe we have just one other sub section "Types" for the different types w/ an explanation, additional arguments, and roughly documents the response?

Rough idea:
- Analytics
  - Overview
    - Brief sentence or two. Touch on the ability to pull video, platform, customer, subscription, and income analytics. Supports both aggregate + time series. bla bla
  - Request / Response
    - Table of common attributes and their definition
    - Example request calls in each client library
    - Example response structure showing (by, from, to, data: {}, etc)
  - Types
    - Table of each type, additional arguments, definition

For documenting the common attributes + types, I like the table structure that videos uses http://dev.vhx.tv/docs/api/#videos.

Do you guys like this approach? If so, we should fully plan out hierarchy before building anymore.

**Comment by scottusrobus** [comment]
@ksheurs that approach sounds great to me!

**Comment by scottusrobus** [comment]
#### Client Libraries:

PRs for Node and PHP client libraries (will merge those in after some more testing)
https://github.com/vhx/vhx-php/pull/13
https://github.com/vhx/vhx-node/pull/11

I can assist adding code examples to this PR. 

#### Node

``` javascript
// defintion
vhx.analytics.report();

// example request
vhx.analytics.report({
  type: 'video',
  by: 'month',
  from: 'today',
  to: '1-year-ago'
}, function(err, report) {
  // asynchronously called
});
```

#### PHP

``` php
// defintion
\VHX\Analytics::report();

// example request
$report = \VHX\Analytics::report(array(
  'type' => 'video',
  'by' => 'month',
  'from' => 'today',
  'to' => '1-year-ago'
));
```

**Comment by osetinsky** [comment]
@ksheurs @scottusrobus thanks for the feedback. Makes sense about combining the different analytics types into one section with multiple examples. I'll hash out a final structure tomorrow before I finish it.

@scottusrobus I can include the new Node/PHP code examples for you. Thanks for including those! 

@sgrshah maybe we can discuss the Ruby client tomorrow?

**Comment by sgrshah** [comment]
@osetinsky @scottusrobus 👍  to adding dashboard analytics and integrating with ruby gem.

@osetinsky let's chat later today!

**Comment by sgrshah** [comment]
A few people have asked about this lately. Should we revisit this?

**Comment by osetinsky** [comment]
Yes probably, keeping in mind deadlines for AVOD/mylist/4k. We'll have new
advertising fields to address as well, unless you meant for video analytics
in particular.

**Comment by scottusrobus** [comment]
Good question! If we omit the `video_id` param does it currently work? Or do we only support per video at the moment? I would think yeah it makes sense that no `video_id`  means an aggregate report of all videos.
cc @osetinsky

**Comment by ksheurs** [comment]
Yea we don't support aggregate now (AFAIK), just thinking for the future re: the docs we put in place now. But sounds good!

**Comment by osetinsky** [comment]
@scottusrobus video_id is currently required (only per video at the moment). An aggregate video report would be nice, though in the Asana task where @sgrshah and I laid out the different reports' parameters, we were using "aggregate" to refer to non-time series reports (not all videos).

**Comment by scottusrobus** [comment]
cool makes sense! thanks for the clarity.

i'm working on adding a dropdown so people can change the response example. but once that's ready, we can do a final review and hopefully merge.

**Comment by scottusrobus** [comment]
This should be ready to go aside from adding the Ruby client examples (which I believe are coming soon).

Since there are a lot of different types of analytic requests, I added a dropdown so you can change the example client library implementations and json response. This setup could be the beginnings of a useful way for us to better automate our examples by pulling from JSON output files generated from crystal (Been talking to @seanpdoyle about this).

screen shot 2016-10-31 at 11 32 56 am

**Comment by seanpdoyle** [comment]
Related to https://github.com/vhx/vhx-ruby/pull/5

**Pull request merged**
